# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Node.js CI Vue Framwork

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [v22.12.0]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
        cache-dependency-path: |
          /beterng/beterng.github.io/projects/vuejs/letmecook/package-lock.json
          /beterng/beterng.github.io/projects/vuejs/letmecook/package.json
          /beterng/beterng.github.io/projects/vuejs/letmecook/jsconfig.json
          /beterng/beterng.github.io/projects/vuejs/letmecook/build-script.json
    - run: npm install vue
    - run: cd letmecook
    - run: npm install
    - run: npm run build
    - run: npm run preview

